notaFS:

.word SILEN
.word MI
.word MI

.word LA
.word LA
.word LA
.word SI

.word DOH
.word DOH
.word DOH
.word REH

.word SI
.word SI
.word LA
.word SOL

.word LA
.word SILEN
.word MI
.word MI

.word LA
.word LA
.word LA
.word SI

.word DOH
.word DOH
.word DOH
.word REH

@ ENDLINE

.word SI
.word SI
.word LA
.word SOL

.word LA
.word SILEN
.word MI
.word MI

.word LA
.word LA
.word LA
.word DOH

.word REH
.word REH
.word REH
.word MIH

.word FAH
.word FAH
.word MIH
.word REH

.word MIH
.word LA
.word SILEN
.word LA
.word DOH

.word DOH
.word DOH
.word REH

@ ENDLINE

.word MIH
.word LA
.word SILEN
.word LA
.word DOH

.word SI
.word SI
.word DOH
.word LA

.word SI
.word SILEN

.word MIH
.word SILEN

.word FAH
.word SILEN

.word MIH
.word MIH
.word MIH

.word MIH
.word REH
.word SILEN

.word RE
.word SILEN

@ ENDLINE

.word DOH
.word SILEN

.word DOH
.word REH
.word SI

.word LA
.word SILEN
.word LA
.word SI

.word DOH
.word REH
.word MIH

.word REH
.word DOH
.word SI

.word DOH
.word REH
.word MIH

.word REH
.word SILEN
.word DOH
.word REH

.word MIH
.word REH
.word DOH

@ ENDLINE

.word SI
.word DOH
.word SI

.word LA
.word SI
.word SOL 

.word LA
.word SILEN
.word LA
.word SI

.word DOH
.word REH
.word MIH

.word REH
.word DOH
.word SI

.word DOH
.word REH
.word MIH

.word REH
.word SILEN
.word LA
.word LA

.word DOH
.word DOH
.word REH

duratFS:

.word BL
.word COR
.word COR

.word NG
.word NG
.word COR
.word COR

.word NG
.word NG
.word COR
.word COR

.word NG
.word NG
.word COR
.word COR

.word NG
.word NG
.word COR
.word COR

.word NG
.word NG
.word COR
.word COR

.word NG
.word NG
.word COR
.word COR

@ ENDLINE

.word NG
.word NG
.word COR
.word COR

.word NG
.word NG
.word COR
.word COR

.word NG
.word NG
.word COR
.word COR

.word NG
.word NG
.word COR
.word COR

.word NG
.word NG
.word COR
.word COR

.word COR
.word COR
.word NG
.word COR
.word COR

.word NG
.word NG
.word NG

@ ENDLINE

.word COR
.word COR
.word NG
.word COR
.word COR

.word NG
.word NG
.word COR
.word COR

.word NG
.word BL

.word NG
.word BL

.word NG
.word BL

.word NG
.word NG
.word NG

.word COR
.word COR
.word BL

.word NG
.word BL

@ ENDLINE

.word NG
.word BL

.word NG
.word NG
.word NG

.word NG
.word NG
.word COR
.word COR

.word BL
.word COR
.word COR

.word NG
.word NG
.word NG

.word NG
.word NG
.word NG

.word NG
.word NG
.word COR
.word COR

.word BL
.word COR
.word COR

@ ENDLINE

.word NG
.word NG
.word NG

.word NG
.word NG
.word NG

.word NG
.word NG
.word COR
.word COR

.word BL
.word COR
.word COR

.word NG
.word NG
.word NG

.word NG
.word NG
.word NG

.word NG
.word NG
.word COR
.word COR

.word NG
.word NG
.word NG
